### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by shanmukhateja** [feross/stream-to-blob#12]
After 3 days of torturing myself getting a ~createDecipheriv.update~ to play nice with ~URL.createObjectURL~, I've lost all hope and was preparing myself to get an earful from the manager when I stumbled across your package.

Its a god-send. Thank you so much for maintaining this package.

I'd like to buy you a beer for this. Could you add like a Paypal link I could use?

**Comment by feross** [comment]
Haha, thanks for the kind note!

You can support me on Patreon here: https://www.patreon.com/feross Or soon on GitHub Sponsors here: https://github.com/users/feross/sponsorship If you just want to use Paypal, my address is https://www.paypal.me/feross
